update csv tests to loop over data.csv input

diff --git a/test/test-csv b/test/test-csv
--- a/test/test-csv
+++ b/test/test-csv
@@ -1,27 +1,114 @@
 #!/bin/bash
 
-wd=$(pwd)
-end_match="sv/files"
-end_match_len=${#end_match}
-wd_len=${#wd}
-i=$((wd_len-end_match_len))
+# wd=$(pwd)
+# end_match="sv/files"
+# end_match_len=${#end_match}
+# wd_len=${#wd}
+# i=$((wd_len-end_match_len))
+# 
+# if [[ "${wd:$i}" != "sv/files" ]]; then
+#     echo "Error: must run the test from the sv/files directory" >&2
+#     exit 1
+# fi
+# 
+# . ns delete wd end_match end_match_len wd_len i
+# 
+# mkdir -p sv_test
+# cp ../test/data.csv sv_test/
+# echo > sv_test/data2.csv
+# 
+# mkdir -p sv_project
+# touch sv_project/backlog.csv
+# cp sv_project/backlog.csv ../project_backlog.csv
+# 
+# sv_file=sv_test/data.csv
 
-if [[ "${wd:$i}" != "sv/files" ]]; then
-    echo "Error: must run the test from the sv/files directory" >&2
-    exit 1
-fi
+test_csv_file="${BASH_SOURCE[0]}"
+test_dir="${test_csv_file%/*}"
 
-. ns delete wd end_match end_match_len wd_len i
+virtual_csv=$(cat "${test_dir}/data.csv")
+virtual_csv="virtual://${virtual_csv}"
 
-mkdir -p sv_test
-cp ../test/data.csv sv_test/
-echo > sv_test/data2.csv
+max_min=`sqlite3 :memory: <<EOF
+create table data(num,name,column_data,is_multiline);
+.mode csv
+.import --csv --skip 1 "${test_dir}/data.csv" data
+.mode list
+select min(num),max(num) from data;
+EOF
+`
 
-mkdir -p sv_project
-touch sv_project/backlog.csv
-cp sv_project/backlog.csv ../project_backlog.csv
+max_min=$(echo "${max_min}")
 
-sv_file=sv_test/data.csv
+min=$(echo "$max_min" | cut -d "|" -f1)
+max=$(echo "$max_min" | cut -d "|" -f2)
+
+for ((i=min;i<=max;i++)); do
+    # if [[ $i -ne 5 ]]; then
+    #     continue
+    # fi
+    res=`sqlite3 :memory: <<EOF
+create table data(num,name,column_data,is_multiline);
+.mode csv
+.import --csv --skip 1 "${test_dir}/data.csv" data
+.mode list
+select name,is_multiline from data where num='${i}';
+EOF
+`
+    res_name=$(echo "$res" | cut -d "|" -f1)
+    res_is_multiline=$(echo "$res" | cut -d "|" -f2)
+
+    res_column_data=`sqlite3 :memory: <<EOF
+create table data(num,name,column_data,is_multiline);
+.mode csv
+.import --csv --skip 1 "${test_dir}/data.csv" data
+.mode list
+select column_data||'END' column_data from data where num='${i}';
+EOF
+`
+    res_column_data_len=${#res_column_data}; ((res_column_data_len-=3))
+    res_column_data="${res_column_data:0:$res_column_data_len}"
+
+    # Load Test
+    test="Row ${i} Load Test - ${res_name}..."
+    sv_num="${i}"
+    sv_file="$virtual_csv"
+    . ns run load
+    # echo "[[${res_column_data}]]"
+    # echo "VS:"
+    # echo "[[${sv_column_data}]]"
+    if [[ -z "$sv_name" || "$sv_name" != "$res_name"  || ${sv_is_multiline} -ne ${res_is_multiline} || ${sv_num} -ne ${i} || "${sv_column_data}" != "${res_column_data}" ]]; then
+        echo "${test}...FAIL"
+    else
+        echo "${test}...PASS"
+    fi
+    # res* vars are used in addtl. tests (deleted at the end of each iteration)
+    . ns delete sv_file sv_num sv_name sv_is_multiline sv_column_data sv_row
+    . ns delete test
+
+    # Add Test
+    test="Row ${i} Add Test - ${res_name}..."
+    sv_file="$virtual_csv"
+    sv_num="${i}"
+    . ns run load        # loads in all sv_vars needed
+    . ns delete sv_row
+    sv_file="virtual://num,name,column_data,is_multiline" # adding it to a new (blank file)
+    . ns run add  # problem!!
+    . ns delete sv_name sv_column_data sv_is_multiline
+    . ns run load
+    if [[ -z "$sv_name" || "$sv_name" != "$res_name"  || ${sv_is_multiline} -ne ${res_is_multiline} || ${sv_num} -ne ${i} || "${sv_column_data}" != "${res_column_data}" ]]; then
+        echo "${test}...FAIL"
+    else
+        echo "${test}...PASS"
+    fi
+    . ns delete sv_file sv_num sv_name sv_is_multiline sv_column_data sv_row
+    . ns delete test
+
+    . ns delete res res_name res_is_multiline res_column_data res_column_data_len
+done
+
+exit 1
+
 sv_num=1
 . ns run load
 test="Row ${sv_num} Load Test - ${sv_name}..."
