add failing add tests

diff --git a/test/test-user-scenarios b/test/test-user-scenarios
--- a/test/test-user-scenarios
+++ b/test/test-user-scenarios
@@ -85,4 +85,49 @@ else
     echo "${test}...PASS"
 fi
 
-# echo "$sv_file"
+. ns delete "sv_*"
+. ns delete d_col_cnt
+
+test="US5 - Adding empty var in row, then load it and re-save it"
+sv_file=sv_test/user-scenarios-empty-var-test.csv
+if [[ -f "$sv_file" ]]; then
+    rm "$sv_file"
+fi
+sv_empty=
+sv_other=1
+. ns run add
+empty_var_line=$(tail -1 "$sv_file")
+capture_row_no="$sv_row"
+. ns run load
+. ns run save # 2>&1 1>>/dev/null
+wcl=$(cat "$sv_file" | wc -l)
+if [[ $wcl -ne 3 && "$sv_row" != 2 && "$capture_row_no" != "1" && "$empty_var_line" != "1," && "$empty_var_line" != ",1" ]]; then
+    echo "${test}...FAIL"
+else
+    echo "${test}...PASS"
+fi
+
+. ns delete "sv_*"
+. ns delete wcl empty_var_line capture_row_no
+
+test="US6 - Omitted column fails to add row"
+sv_file="sv_test/user-scenarios-omitted.csv"
+if [[ -f "$sv_file" ]]; then
+    rm "$sv_file"
+fi
+echo "title,other,stuff" >> "$sv_file"
+sv_title="My Title: My subtitle, and stuff"
+sv_other="my data"
+# sv_stuff gets omitted
+. ns run add # 2>&1 1>>/dev/null
+ec=$?
+wcl=$(cat "$sv_file" | wc -l)
+
+if [[ $wcl -ne 1 || $ec -lt 1 ]]; then
+    echo "${test}...FAIL"
+else
+    echo "${test}...PASS"
+fi
+
+. ns delete "sv_*"
+. ns delete ec
